/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as applicationRouteRouteImport } from './routes/(application)/route'
import { Route as applicationIndexRouteImport } from './routes/(application)/index'
import { Route as authPagesLoginIndexRouteImport } from './routes/(auth-pages)/login/index'
import { Route as applicationUploadsIndexRouteImport } from './routes/(application)/uploads/index'
import { Route as applicationSessionsIndexRouteImport } from './routes/(application)/sessions/index'
import { Route as applicationAttendeesIndexRouteImport } from './routes/(application)/attendees/index'

const applicationRouteRoute = applicationRouteRouteImport.update({
  id: '/(application)',
  getParentRoute: () => rootRouteImport,
} as any)
const applicationIndexRoute = applicationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => applicationRouteRoute,
} as any)
const authPagesLoginIndexRoute = authPagesLoginIndexRouteImport.update({
  id: '/(auth-pages)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const applicationUploadsIndexRoute = applicationUploadsIndexRouteImport.update({
  id: '/uploads/',
  path: '/uploads/',
  getParentRoute: () => applicationRouteRoute,
} as any)
const applicationSessionsIndexRoute =
  applicationSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => applicationRouteRoute,
  } as any)
const applicationAttendeesIndexRoute =
  applicationAttendeesIndexRouteImport.update({
    id: '/attendees/',
    path: '/attendees/',
    getParentRoute: () => applicationRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof applicationIndexRoute
  '/attendees': typeof applicationAttendeesIndexRoute
  '/sessions': typeof applicationSessionsIndexRoute
  '/uploads': typeof applicationUploadsIndexRoute
  '/login': typeof authPagesLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof applicationIndexRoute
  '/attendees': typeof applicationAttendeesIndexRoute
  '/sessions': typeof applicationSessionsIndexRoute
  '/uploads': typeof applicationUploadsIndexRoute
  '/login': typeof authPagesLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(application)': typeof applicationRouteRouteWithChildren
  '/(application)/': typeof applicationIndexRoute
  '/(application)/attendees/': typeof applicationAttendeesIndexRoute
  '/(application)/sessions/': typeof applicationSessionsIndexRoute
  '/(application)/uploads/': typeof applicationUploadsIndexRoute
  '/(auth-pages)/login/': typeof authPagesLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attendees' | '/sessions' | '/uploads' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attendees' | '/sessions' | '/uploads' | '/login'
  id:
    | '__root__'
    | '/(application)'
    | '/(application)/'
    | '/(application)/attendees/'
    | '/(application)/sessions/'
    | '/(application)/uploads/'
    | '/(auth-pages)/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  applicationRouteRoute: typeof applicationRouteRouteWithChildren
  authPagesLoginIndexRoute: typeof authPagesLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(application)': {
      id: '/(application)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof applicationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(application)/': {
      id: '/(application)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof applicationIndexRouteImport
      parentRoute: typeof applicationRouteRoute
    }
    '/(auth-pages)/login/': {
      id: '/(auth-pages)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(application)/uploads/': {
      id: '/(application)/uploads/'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof applicationUploadsIndexRouteImport
      parentRoute: typeof applicationRouteRoute
    }
    '/(application)/sessions/': {
      id: '/(application)/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof applicationSessionsIndexRouteImport
      parentRoute: typeof applicationRouteRoute
    }
    '/(application)/attendees/': {
      id: '/(application)/attendees/'
      path: '/attendees'
      fullPath: '/attendees'
      preLoaderRoute: typeof applicationAttendeesIndexRouteImport
      parentRoute: typeof applicationRouteRoute
    }
  }
}

interface applicationRouteRouteChildren {
  applicationIndexRoute: typeof applicationIndexRoute
  applicationAttendeesIndexRoute: typeof applicationAttendeesIndexRoute
  applicationSessionsIndexRoute: typeof applicationSessionsIndexRoute
  applicationUploadsIndexRoute: typeof applicationUploadsIndexRoute
}

const applicationRouteRouteChildren: applicationRouteRouteChildren = {
  applicationIndexRoute: applicationIndexRoute,
  applicationAttendeesIndexRoute: applicationAttendeesIndexRoute,
  applicationSessionsIndexRoute: applicationSessionsIndexRoute,
  applicationUploadsIndexRoute: applicationUploadsIndexRoute,
}

const applicationRouteRouteWithChildren =
  applicationRouteRoute._addFileChildren(applicationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  applicationRouteRoute: applicationRouteRouteWithChildren,
  authPagesLoginIndexRoute: authPagesLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
